// Generates data/source/ggpk-poe2/CATALOG.md — the durable "start here" map for
// a fresh session with no prior context: every mirrored table, its row count,
// what it references, and how many tables reference it. Derived from the pinned
// schema + the raw mirror; no network.
import fs from 'node:fs';
import fsp from 'node:fs/promises';
import path from 'node:path';
import { GGPK_DIR, TABLES_DIR, loadSchema, tablePath } from './dat.js';

/** Row count without a full parse: the .datc64 header is a uint32 LE row count. */
export function rowCountOf(name, dir = TABLES_DIR) {
  const fd = fs.openSync(tablePath(name, dir), 'r');
  try {
    const b = Buffer.alloc(4);
    fs.readSync(fd, b, 0, 4, 0);
    return b.readUInt32LE(0);
  } finally {
    fs.closeSync(fd);
  }
}

/** table name -> Set of table names that reference it (via foreignrow columns). */
export function reverseRefs(schema) {
  const refBy = new Map();
  for (const t of schema.raw.tables) {
    for (const c of t.columns) {
      const ref = c.references?.table;
      if (!ref) continue;
      if (!refBy.has(ref)) refBy.set(ref, new Set());
      refBy.get(ref).add(t.name);
    }
  }
  return refBy;
}

export async function writeCatalog({ dir = TABLES_DIR, out = path.join(GGPK_DIR, 'CATALOG.md') } = {}) {
  const schema = await loadSchema();
  const refBy = reverseRefs(schema);
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.datc64')).sort();

  const lines = [];
  lines.push('# GGPK data mirror — table catalog');
  lines.push('');
  lines.push('Generated by `npm run dat -- catalog` (and automatically after `npm run fetch:dat`).');
  lines.push('Raw `.datc64` tables mirrored from ggpk.exposed; column names from the pinned dat-schema.');
  lines.push('');
  lines.push('Fresh-session workflow: `npm run dat -- grep <keyword>` to find a table, ');
  lines.push('`npm run dat -- schema <Table>` for its columns + relationships, ');
  lines.push('`npm run dat -- dump <Table> --resolve` to read rows with foreign keys resolved.');
  lines.push('');
  lines.push(`${files.length} tables mirrored.`);
  lines.push('');
  lines.push('| Table | Rows | References | Ref\'d by |');
  lines.push('|---|--:|---|--:|');

  for (const f of files) {
    const base = f.replace(/\.datc64$/, '');
    const def = schema.byName.get(base);
    const display = def?.name ?? base;
    let rows = '?';
    try { rows = String(rowCountOf(base, dir)); } catch { /* leave ? */ }
    const refs = def
      ? [...new Set(def.columns.map((c) => c.references?.table).filter(Boolean))].join(', ')
      : '_(no schema)_';
    const rb = def ? (refBy.get(def.name)?.size ?? 0) : 0;
    lines.push(`| \`${display}\` | ${rows} | ${refs} | ${rb} |`);
  }
  lines.push('');

  await fsp.writeFile(out, lines.join('\n'));
  return { out, count: files.length };
}
